/**
 * Dados mockados para demonstração inicial
 * Inclui treinos de exemplo para visualizar a aplicação em funcionamento
 */

import { Workout } from '@/types';

export const MOCK_WORKOUTS: Workout[] = [
  // Semana 1 - Ficha A
  {
    id: 'mock-1',
    date: '2026-04-20',
    sheet: 'A',
    exercise: 'Supino reto com barra',
    muscleGroup: 'Peito',
    load: 60,
    loadType: 'bilateral',
    reps: 8,
    sets: 3,
    notes: 'Bom aquecimento',
  },
  {
    id: 'mock-2',
    date: '2026-04-20',
    sheet: 'A',
    exercise: 'Supino inclinado com halteres',
    muscleGroup: 'Peito',
    load: 24,
    loadType: 'bilateral',
    reps: 10,
    sets: 3,
  },
  {
    id: 'mock-3',
    date: '2026-04-20',
    sheet: 'A',
    exercise: 'Tríceps francês',
    muscleGroup: 'Tríceps',
    load: 20,
    loadType: 'unilateral',
    reps: 12,
    sets: 3,
  },
  {
    id: 'mock-4',
    date: '2026-04-20',
    sheet: 'A',
    exercise: 'Elevação lateral',
    muscleGroup: 'Ombros',
    load: 12,
    loadType: 'bilateral',
    reps: 12,
    sets: 3,
  },

  // Semana 1 - Ficha B
  {
    id: 'mock-5',
    date: '2026-04-22',
    sheet: 'B',
    exercise: 'Puxada frente pulley',
    muscleGroup: 'Costas',
    load: 70,
    loadType: 'unilateral',
    reps: 8,
    sets: 3,
  },
  {
    id: 'mock-6',
    date: '2026-04-22',
    sheet: 'B',
    exercise: 'Rosca W',
    muscleGroup: 'Bíceps',
    load: 30,
    loadType: 'bilateral',
    reps: 10,
    sets: 3,
  },

  // Semana 1 - Ficha C
  {
    id: 'mock-7',
    date: '2026-04-24',
    sheet: 'C',
    exercise: 'Agachamento',
    muscleGroup: 'Pernas',
    load: 80,
    loadType: 'unilateral',
    reps: 8,
    sets: 4,
  },
  {
    id: 'mock-8',
    date: '2026-04-24',
    sheet: 'C',
    exercise: 'Leg press 45',
    muscleGroup: 'Pernas',
    load: 200,
    loadType: 'unilateral',
    reps: 10,
    sets: 3,
  },

  // Semana 2 - Ficha A
  {
    id: 'mock-9',
    date: '2026-04-27',
    sheet: 'A',
    exercise: 'Supino reto com barra',
    muscleGroup: 'Peito',
    load: 62,
    loadType: 'bilateral',
    reps: 9,
    sets: 3,
    notes: 'Melhor desempenho',
  },
  {
    id: 'mock-10',
    date: '2026-04-27',
    sheet: 'A',
    exercise: 'Supino inclinado com halteres',
    muscleGroup: 'Peito',
    load: 26,
    loadType: 'bilateral',
    reps: 10,
    sets: 3,
  },
  {
    id: 'mock-11',
    date: '2026-04-27',
    sheet: 'A',
    exercise: 'Tríceps francês',
    muscleGroup: 'Tríceps',
    load: 22,
    loadType: 'unilateral',
    reps: 12,
    sets: 3,
  },

  // Semana 2 - Ficha B
  {
    id: 'mock-12',
    date: '2026-04-29',
    sheet: 'B',
    exercise: 'Puxada frente pulley',
    muscleGroup: 'Costas',
    load: 75,
    loadType: 'unilateral',
    reps: 9,
    sets: 3,
  },
  {
    id: 'mock-13',
    date: '2026-04-29',
    sheet: 'B',
    exercise: 'Rosca W',
    muscleGroup: 'Bíceps',
    load: 32,
    loadType: 'bilateral',
    reps: 10,
    sets: 3,
  },

  // Semana 2 - Ficha C
  {
    id: 'mock-14',
    date: '2026-05-01',
    sheet: 'C',
    exercise: 'Agachamento',
    muscleGroup: 'Pernas',
    load: 85,
    loadType: 'unilateral',
    reps: 8,
    sets: 4,
  },
  {
    id: 'mock-15',
    date: '2026-05-01',
    sheet: 'C',
    exercise: 'Leg press 45',
    muscleGroup: 'Pernas',
    load: 210,
    loadType: 'unilateral',
    reps: 10,
    sets: 3,
  },

  // Semana 3 - Ficha A
  {
    id: 'mock-16',
    date: '2026-05-04',
    sheet: 'A',
    exercise: 'Supino reto com barra',
    muscleGroup: 'Peito',
    load: 65,
    loadType: 'bilateral',
    reps: 10,
    sets: 3,
  },
  {
    id: 'mock-17',
    date: '2026-05-04',
    sheet: 'A',
    exercise: 'Supino inclinado com halteres',
    muscleGroup: 'Peito',
    load: 28,
    loadType: 'bilateral',
    reps: 11,
    sets: 3,
  },
  {
    id: 'mock-18',
    date: '2026-05-04',
    sheet: 'A',
    exercise: 'Tríceps francês',
    muscleGroup: 'Tríceps',
    load: 24,
    loadType: 'unilateral',
    reps: 12,
    sets: 3,
  },
];
